name: symphony_desktop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_grid: ^2.2.0
  audio_video_progress_bar: ^0.11.0
  dart_vlc: ^0.4.0
  dart_vlc_ffi: ^0.2.0+1
  get: ^4.6.5
  flutter_launcher_icons: ^0.13.0
  ionicons: ^0.2.2
  get_storage: ^2.1.1
  flutter_acrylic: ^1.1.2
  bitsdojo_window: ^0.1.5
  google_fonts: ^4.0.3
  text_scroll: ^0.2.0
  youtube_explode_dart: ^1.12.4
  just_audio: ^0.9.32
  just_audio_windows: ^0.2.0
  just_audio_background: ^0.0.1-beta.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
