name: symphony_desktop
description: A music player via streaming like Spotify and Deezer.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-165.1.beta"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_acrylic: ^1.0.0+2
  get: ^4.6.5
  collection: ^1.16.0
  google_fonts: ^3.0.1
  audio_video_progress_bar: ^0.10.0
  bitsdojo_window: ^0.1.2
  syncfusion_flutter_sliders: ^20.2.36
  syncfusion_flutter_core: ^20.2.36
  cached_network_image: ^3.2.1
  ionicons: ^0.1.2
  responsive_grid_list: ^1.2.4
  dart_periphery: ^0.9.1
  palette_generator: ^0.3.3+2
  path_provider: ^2.0.11
  dio: ^4.0.6
  just_audio: ^0.9.31
  youtube_explode_dart: ^1.12.3
  just_audio_background: ^0.0.1-beta.9
  just_audio_windows: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  windows:
    generate: true
    image_path: "assets/icons/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
