name: symphony_desktop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_grid: ^2.2.0
  audio_video_progress_bar: ^0.11.0
  dart_vlc: ^0.4.0
  dart_vlc_ffi: ^0.2.0+1
  get: ^4.6.5
  ionicons: ^0.2.2
  get_storage: ^2.1.1
  flutter_acrylic: ^1.1.2
  bitsdojo_window: ^0.1.5
  google_fonts: ^4.0.3
  text_scroll: ^0.2.0
  youtube_explode_dart: ^1.12.4
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true

assets:
  - assets/icon.png

flutter_icons:
  image_path: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"
